on:
  issues:
    types: [opened, reopened, deleted, closed]
name: Slack Issue Notification
jobs:
  slackNotification:
    name: Slack Notification Issue
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification Issue
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: partnereng-issues
          SLACK_COLOR: '#00A86B'
          SLACK_ICON: https://pbs.twimg.com/profile_images/978188446178082817/86ulJdF0.jpg
          SLACK_TITLE: "[${{ github.event.issue.state}}] ${{ github.event.issue.title }} on ${{ github.repository }} :rocket:"
          SLACK_MESSAGE: 'Link: ${{ github.event.issue.html_url }}'
          SLACK_USERNAME: PartnerEngineers
          SLACK_WEBHOOK: ${{ secrets.SLACK_ISSUE_WEBHOOK }}
